// Generated by CoffeeScript 1.6.3
var t9Word;

t9Word = angular.module("t9Word", []);

t9Word.controller("T9Ctrl", function($scope, $filter) {
  $scope.numberSequence = "";
  $scope.words = [];
  $scope.filteredWords = [];
  $scope.currentPage = 0;
  $scope.pageSize = 40;
  $scope.numberOfPages = function() {
    return Math.ceil($scope.filteredWords.length / $scope.pageSize);
  };
  $scope.$watch("query", (function() {
    $scope.filteredWords = $filter("filter")($scope.words, this.last);
    return $scope.currentPage = 0;
  }), true);
  $scope.getWords = function() {
    $scope.words = getPossibleWords($scope.numberSequence);
    $scope.filteredWords = $filter("filter")($scope.words, $scope.query);
    return $scope.currentPage = 0;
  };
  $scope.undoLast = function() {
    $scope.numberSequence = $scope.numberSequence.slice(0, $scope.numberSequence.length - 1);
    return $scope.getWords();
  };
  $scope.clearSequence = function() {
    $scope.numberSequence = "";
    return $scope.getWords();
  };
  $scope.addToSequence = function(num) {
    var okToRun;
    okToRun = true;
    if ($scope.words.length >= 8e5) {
      okToRun = confirm("WARNING: Many Word Combinations - " + "This might take a while, are you sure?");
    }
    if (okToRun) {
      $scope.numberSequence += num;
      return $scope.getWords();
    }
  };
  return $scope.pressPhoneKey = function(ev) {
    var clear, num, undo;
    clear = ev.which === 35;
    undo = ev.which === 42;
    num = void 0;
    if (clear) {
      $scope.clearSequence();
    }
    if (undo) {
      $scope.undoLast();
    }
    num = ev.which - 48;
    if (num >= 0 && num < 10) {
      return $scope.addToSequence(num);
    }
  };
});

t9Word.filter("startFrom", function() {
  return function(input, start) {
    start = parseInt(start, 10);
    return input.slice(start);
  };
});
